- name: Install Python
  hosts: all
  gather_facts: no
  become: yes
  tags:
    - python
  tasks:
    - raw: test -e /usr/bin/python || (apt install -y python-minimal)
      register: cmd_apt_install_python
      changed_when: "cmd_apt_install_python.stdout != ''"

- name: Install Pip
  hosts: all
  become: yes
  tags:
    - pip
  roles:
    - { role: geerlingguy.pip }
