- name: Install Docker
  hosts: docker
  become: yes
  tags:
    - docker
  vars:
    skip_group: True
    skip_swarm: True
  roles:
    - { role: atosatto.docker-swarm }
  tasks:
    - name: install docker-compose if neccessary
      pip:
        name: docker-compose
        version: 1.8.0
        state: present
