- name: Docker Registry
  hosts: docker_registry
  become: yes
  vars:
    docker_registry_path: /opt/docker/registry
    docker_registry_port: 5000
  tasks:
    - name: Create registry data path
      file:
        path: "{{ docker_registry_path }}"
        state: directory
    - name: Create registry config
      copy:
        src: files/docker_registry/config.yml
        dest: "{{ docker_registry_path }}/config.yml"
    - name: Start registry container
      docker_service:
        project_name: registry
        definition:
          version: '2'
          services:
            nginx:
              image: registry:2
              container_name: registry
              restart: unless-stopped
              environment:
                TERM: xterm-256color
                TZ: Asia/Bangkok
              ports:
                - "{{ docker_registry_port }}:5000"
              volumes:
                - "{{ docker_registry_path }}/config.yml:/etc/docker/registry/config.yml"
                - "{{ docker_registry_path }}/data:/var/lib/registry"
